2024-11-22 18:38:16,843 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-22 18:38:16,844 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-22 18:38:20,218 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-22 18:38:21,596 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-22 18:38:21,651 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 44 строки, в каждой строке 24 символа. Определите информационный объём рассказа в Кбайтах в кодировке Windows-1251. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-22 18:38:21,742 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:38:21,744 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 99, in callback_query
    users[user_id]['state'] = STATE_WAITING_ANSWER
    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-22 18:38:24,845 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 24 (type: <class 'str'>)
2024-11-22 18:38:24,846 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:38:24,847 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 118, in handle_message
    current_state = users[user_id]['state']
                    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-22 18:38:24,892 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 24 (type: <class 'str'>)
2024-11-22 18:38:27,850 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:38:27,852 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 118, in handle_message
    current_state = users[user_id]['state']
                    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-22 18:42:57,412 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-22 18:42:57,415 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-22 18:43:00,679 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-22 18:43:04,051 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-22 18:43:04,216 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 34 строки, в каждой строке 40 символов. Определите информационный объём рассказа в Кбайтах в кодировке UTF-8. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-22 18:43:04,369 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:43:04,371 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 99, in callback_query
    users[user_id]['state'] = STATE_WAITING_ANSWER
    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-22 18:43:07,536 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 22 (type: <class 'str'>)
2024-11-22 18:43:07,537 - TeleBot - ERROR - Infinity polling exception: 'dict_keys' object is not subscriptable
2024-11-22 18:43:07,539 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 117, in handle_message
    logger.info(f'users.keys()[0] {users.keys()[0]}')
                                   ~~~~~~~~~~~~^^^
TypeError: 'dict_keys' object is not subscriptable

2024-11-22 18:43:07,666 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 22 (type: <class 'str'>)
2024-11-22 18:43:10,542 - TeleBot - ERROR - Infinity polling exception: 'dict_keys' object is not subscriptable
2024-11-22 18:43:10,544 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 117, in handle_message
    logger.info(f'users.keys()[0] {users.keys()[0]}')
                                   ~~~~~~~~~~~~^^^
TypeError: 'dict_keys' object is not subscriptable

2024-11-22 18:43:48,095 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-22 18:43:48,097 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-22 18:43:49,441 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-22 18:43:50,531 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-22 18:43:50,674 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 7 страниц, на каждой странице 38 строк, в каждой строке 24 символа. Определите информационный объём рассказа в Кбайтах в кодировке Unicode, в которой каждый символ кодируется 16 битами. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-22 18:43:50,777 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:43:50,777 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 99, in callback_query
    users[user_id]['state'] = STATE_WAITING_ANSWER
    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-22 18:43:52,737 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 22 (type: <class 'str'>)
2024-11-22 18:43:52,737 - __main__ - INFO - users.keys() dict_keys([])
2024-11-22 18:43:53,781 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:43:53,784 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 119, in handle_message
    current_state = users[user_id]['state']
                    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-22 18:50:05,304 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-22 18:50:05,306 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-22 18:50:06,564 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-22 18:50:07,729 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-22 18:50:07,808 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 34 строки, в каждой строке 40 символов. Определите информационный объём рассказа в Кбайтах в кодировке UTF-8. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-22 18:50:07,897 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:50:07,898 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 99, in callback_query
    users[user_id]['state'] = STATE_WAITING_ANSWER
    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-22 18:50:10,431 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 2 (type: <class 'str'>)
2024-11-22 18:50:10,431 - __main__ - INFO - Current keys in 'users' dictionary: 
2024-11-22 18:50:10,902 - TeleBot - ERROR - Infinity polling exception: 1845480898
2024-11-22 18:50:10,904 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 122, in handle_message
    current_state = users[user_id]['state']
                    ~~~~~^^^^^^^^^
KeyError: 1845480898

2024-11-24 16:23:10,993 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-24 16:23:10,994 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-24 16:23:12,612 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-24 16:23:13,925 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-24 16:23:13,992 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 8 страниц, на каждой странице 42 строки, в каждой строке 48 символов. Определите информационный объём рассказа в Кбайтах в кодировке ASCII. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-24 16:23:17,082 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 22 (type: <class 'str'>)
2024-11-24 16:23:17,082 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>)
2024-11-24 16:25:11,822 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-24 16:25:11,823 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-24 16:25:13,373 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-24 16:25:14,376 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-24 16:25:14,433 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 34 строки, в каждой строке 40 символов. Определите информационный объём рассказа в Кбайтах в кодировке UTF-8. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-24 16:25:30,453 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 7 (type: <class 'str'>)
2024-11-24 16:25:30,453 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>)
2024-11-24 16:25:47,135 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-24 16:25:47,136 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-24 16:25:48,498 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-24 16:25:49,266 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-24 16:25:49,326 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 2 страницы, на каждой странице 43 строки, в каждой строке 24 символа. Определите информационный объём рассказа в Кбайтах в кодировке UTF-32. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-24 16:26:54,249 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-24 16:26:54,250 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-24 16:26:56,085 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-24 16:26:57,243 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-24 16:26:57,308 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 2 страницы, на каждой странице 43 строки, в каждой строке 24 символа. Определите информационный объём рассказа в Кбайтах в кодировке UTF-32. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-24 16:27:01,686 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 8 (type: <class 'str'>)
2024-11-24 16:27:01,686 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>)
2024-11-24 16:27:08,978 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-24 16:27:08,980 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-24 16:27:10,752 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-24 16:27:11,762 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-24 16:27:11,822 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 8 страниц, на каждой странице 42 строки, в каждой строке 48 символов. Определите информационный объём рассказа в Кбайтах в кодировке ASCII. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-24 16:27:15,511 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 22 (type: <class 'str'>)
2024-11-24 16:27:15,511 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>)
2024-11-30 17:45:32,585 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-30 17:45:32,586 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-30 17:45:34,644 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-30 17:45:35,821 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-11-30 17:45:35,893 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 34 строки, в каждой строке 40 символов. Определите информационный объём рассказа в Кбайтах в кодировке UTF-8. Ответ округлите до целого. (type: <class 'dict'>)
2024-11-30 17:45:41,371 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 54 (type: <class 'str'>)
2024-11-30 17:45:41,372 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>)
2024-11-30 17:46:30,108 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-30 17:46:30,108 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-30 17:46:31,547 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-30 17:46:32,552 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-11-30 17:46:34,968 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-11-30 17:55:28,465 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:28,465 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:31,900 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:31,901 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:32,223 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:32,224 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:33,118 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-30 17:55:33,118 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-30 17:55:33,228 - TeleBot - ERROR - Infinity polling exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-11-30 17:55:35,779 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:35,781 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:39,451 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:39,452 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:40,508 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:40,510 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:44,191 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:44,192 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:46,246 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:46,247 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:49,806 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:49,806 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:55:53,866 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-11-30 17:55:53,866 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-11-30 17:56:02,993 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-30 17:56:02,994 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-30 17:56:04,399 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-30 17:56:05,601 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-11-30 17:56:05,605 - TeleBot - ERROR - Infinity polling exception: cannot access local variable 'number_of_tests' where it is not associated with a value
2024-11-30 17:56:05,606 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\aleks\School python projects\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aleks\School python projects\-EduDuelOGE\main.py", line 93, in callback_query
    number_of_tests = users[user_id][number_of_tests]
                                     ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'number_of_tests' where it is not associated with a value

2024-11-30 17:57:43,118 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-11-30 17:57:43,121 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-11-30 17:57:44,458 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-11-30 17:57:45,265 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-01 16:43:36,252 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-12-01 16:43:36,253 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-12-01 16:43:37,476 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-01 16:43:38,969 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-01 16:43:56,358 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-01 16:43:56,772 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 34 строки, в каждой строке 40 символов. Определите информационный объём рассказа в Кбайтах в кодировке UTF-8. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-01 16:44:16,745 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 7 (type: <class 'str'>)
2024-12-01 16:44:16,745 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>)
2024-12-01 17:12:37,959 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-12-01 17:12:37,962 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-12-01 17:13:07,671 - __main__ - INFO - User 180616110 (type: <class 'int'>) sent /start command
2024-12-01 17:13:07,672 - __main__ - INFO - Registering new user: 180616110 (type: <class 'int'>)
2024-12-01 17:13:19,627 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-01 17:13:39,954 - __main__ - INFO - User 180616110 (type: <class 'int'>) selected callback data: cb_stats (type: <class 'str'>)
2024-12-01 17:13:41,585 - __main__ - INFO - User 180616110 (type: <class 'int'>) selected callback data: cb_setting (type: <class 'str'>)
2024-12-01 17:13:43,241 - __main__ - INFO - User 180616110 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-01 17:13:43,675 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-01 17:13:43,775 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 44 строки, в каждой строке 24 символа. Определите информационный объём рассказа в Кбайтах в кодировке Windows-1251. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-01 17:13:47,856 - __main__ - INFO - User 180616110 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-01 17:13:47,923 - __main__ - INFO - User 180616110 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 34 строки, в каждой строке 40 символов. Определите информационный объём рассказа в Кбайтах в кодировке UTF-8. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-01 17:13:51,132 - __main__ - INFO - User 180616110 (type: <class 'int'>) sent a message: 24 (type: <class 'str'>)
2024-12-01 17:13:51,133 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>), 180616110 (type: <class 'int'>)
2024-12-01 17:13:58,255 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 21 (type: <class 'str'>)
2024-12-01 17:13:58,256 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>), 180616110 (type: <class 'int'>)
2024-12-01 17:19:45,895 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-12-01 17:19:45,896 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-12-01 17:19:47,417 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-01 17:19:48,460 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-01 17:19:48,537 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 44 строки, в каждой строке 24 символа. Определите информационный объём рассказа в Кбайтах в кодировке Windows-1251. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-01 17:19:52,162 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 11 (type: <class 'str'>)
2024-12-01 17:19:52,163 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>), 180616110 (type: <class 'int'>)
2024-12-01 17:19:57,647 - __main__ - INFO - User 180616110 (type: <class 'int'>) sent /start command
2024-12-01 17:19:57,649 - __main__ - INFO - User 180616110 (type: <class 'int'>) is already registered
2024-12-01 17:19:59,723 - __main__ - INFO - User 180616110 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-01 17:20:01,225 - __main__ - INFO - User 180616110 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-01 17:20:01,281 - __main__ - INFO - User 180616110 received random question: Рассказ, набранный на компьютере, содержит 8 страниц, на каждой странице 42 строки, в каждой строке 48 символов. Определите информационный объём рассказа в Кбайтах в кодировке ASCII. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-01 17:20:02,773 - __main__ - INFO - User 180616110 (type: <class 'int'>) sent a message: 31 (type: <class 'str'>)
2024-12-01 17:20:02,774 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>), 180616110 (type: <class 'int'>)
2024-12-01 17:20:19,877 - __main__ - INFO - User 180616110 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-01 17:20:19,935 - __main__ - INFO - User 180616110 received random question: Рассказ, набранный на компьютере, содержит 5 страниц, на каждой странице 44 строки, в каждой строке 24 символа. Определите информационный объём рассказа в Кбайтах в кодировке Windows-1251. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-01 17:20:22,067 - __main__ - INFO - User 180616110 (type: <class 'int'>) sent a message: 234 (type: <class 'str'>)
2024-12-01 17:20:22,068 - __main__ - INFO - Current keys in 'users' dictionary: 1845480898 (type: <class 'int'>), 180616110 (type: <class 'int'>)
2024-12-01 17:24:39,081 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent /start command
2024-12-01 17:24:39,083 - __main__ - INFO - User 1845480898 (type: <class 'int'>) is already registered
2024-12-22 19:29:16,925 - __main__ - INFO - User 1845480898 sent /start command
2024-12-22 19:29:16,926 - __main__ - INFO - User 1845480898 is already registered
2024-12-22 19:29:18,519 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-22 19:29:19,784 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-22 19:29:19,837 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 8 страниц, на каждой странице 42 строки, в каждой строке 48 символов. Определите информационный объём рассказа в Кбайтах в кодировке ASCII. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-22 19:44:36,669 - __main__ - INFO - User 1845480898 sent /start command
2024-12-22 19:44:36,671 - __main__ - INFO - User 1845480898 is already registered
2024-12-22 19:44:45,218 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-22 19:44:46,613 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_random (type: <class 'str'>)
2024-12-22 19:44:46,791 - __main__ - INFO - User 1845480898 received random question: Рассказ, набранный на компьютере, содержит 8 страниц, на каждой странице 42 строки, в каждой строке 48 символов. Определите информационный объём рассказа в Кбайтах в кодировке ASCII. Ответ округлите до целого. (type: <class 'dict'>)
2024-12-22 19:44:49,672 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 23 (type: <class 'str'>)
2024-12-22 19:44:54,618 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-22 19:44:56,737 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-22 19:44:56,989 - TeleBot - ERROR - Infinity polling exception: 'seria_of_questions'
2024-12-22 19:44:56,991 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 logger_level=logger_level, allowed_updates=allowed_updates, restart_on_change=False,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 *args, **kwargs)
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            logger_level=logger_level, allowed_updates=allowed_updates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\aleks\-EduDuelOGE\main.py", line 83, in callback_query
    user['seria_of_questions'].extend(questions)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'seria_of_questions'

2024-12-22 19:44:58,281 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-22 19:44:59,992 - TeleBot - ERROR - Infinity polling exception: 'seria_of_questions'
2024-12-22 19:44:59,995 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 logger_level=logger_level, allowed_updates=allowed_updates, restart_on_change=False,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 *args, **kwargs)
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            logger_level=logger_level, allowed_updates=allowed_updates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\aleks\-EduDuelOGE\main.py", line 83, in callback_query
    user['seria_of_questions'].extend(questions)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'seria_of_questions'

2024-12-22 19:45:00,138 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-22 19:45:02,996 - TeleBot - ERROR - Infinity polling exception: 'seria_of_questions'
2024-12-22 19:45:02,997 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 logger_level=logger_level, allowed_updates=allowed_updates, restart_on_change=False,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 *args, **kwargs)
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            logger_level=logger_level, allowed_updates=allowed_updates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\aleks\-EduDuelOGE\main.py", line 83, in callback_query
    user['seria_of_questions'].extend(questions)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'seria_of_questions'

2024-12-22 19:45:10,059 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_stats (type: <class 'str'>)
2024-12-22 19:45:11,118 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_stats (type: <class 'str'>)
2024-12-22 19:45:11,314 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_stats (type: <class 'str'>)
2024-12-22 19:45:11,493 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_stats (type: <class 'str'>)
2024-12-22 19:45:11,653 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_stats (type: <class 'str'>)
2024-12-22 19:45:16,782 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_setting (type: <class 'str'>)
2024-12-22 19:45:16,940 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_stats (type: <class 'str'>)
2024-12-22 20:00:14,409 - __main__ - INFO - User 1845480898 sent /start command
2024-12-22 20:00:14,410 - __main__ - INFO - User 1845480898 is already registered
2024-12-22 20:00:16,469 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-22 20:00:17,889 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-22 20:00:18,298 - TeleBot - ERROR - Infinity polling exception: 'seria_of_questions'
2024-12-22 20:00:18,299 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 logger_level=logger_level, allowed_updates=allowed_updates, restart_on_change=False,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 *args, **kwargs)
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            logger_level=logger_level, allowed_updates=allowed_updates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\aleks\-EduDuelOGE\.venv\Lib\site-packages\telebot\__init__.py", line 8945, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\aleks\-EduDuelOGE\main.py", line 84, in callback_query
    user['seria_of_questions'].extend(questions)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'seria_of_questions'

2024-12-22 20:02:03,958 - __main__ - INFO - User 1845480898 sent /start command
2024-12-22 20:02:03,960 - __main__ - INFO - Registering new user: 1845480898)
2024-12-22 20:02:16,223 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-22 20:02:17,166 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-22 20:06:54,077 - __main__ - INFO - User 1845480898 sent /start command
2024-12-22 20:06:54,078 - __main__ - INFO - User 1845480898 is already registered
2024-12-22 20:06:55,419 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-22 20:06:56,592 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-27 18:16:33,210 - __main__ - INFO - User 1845480898 sent /start command
2024-12-27 18:16:33,212 - __main__ - INFO - User 1845480898 is already registered
2024-12-27 18:16:36,860 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-27 18:16:37,911 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-27 18:30:11,681 - __main__ - INFO - User 1845480898 sent /start command
2024-12-27 18:30:11,686 - __main__ - INFO - User 1845480898 is already registered
2024-12-27 18:30:14,806 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-27 18:30:16,577 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-27 18:30:27,643 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: as (type: <class 'str'>)
2024-12-27 19:09:48,190 - __main__ - INFO - User 1845480898 sent /start command
2024-12-27 19:09:48,195 - __main__ - INFO - User 1845480898 is already registered
2024-12-27 19:09:49,821 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_test (type: <class 'str'>)
2024-12-27 19:09:50,999 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-27 19:09:54,156 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 12 (type: <class 'str'>)
2024-12-27 19:10:03,617 - __main__ - INFO - User 1845480898 (type: <class 'int'>) selected callback data: cb_series (type: <class 'str'>)
2024-12-27 19:10:07,389 - __main__ - INFO - User 1845480898 (type: <class 'int'>) sent a message: 34 (type: <class 'str'>)
